[2023-02-02T17:24:47.138+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag_prac.s3_to_redshift manual__2023-02-02T17:23:42.968181+00:00 [queued]>
[2023-02-02T17:24:47.144+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag_prac.s3_to_redshift manual__2023-02-02T17:23:42.968181+00:00 [queued]>
[2023-02-02T17:24:47.144+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T17:24:47.144+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-02-02T17:24:47.144+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T17:24:47.158+0000] {taskinstance.py:1383} INFO - Executing <Task(S3ToRedshiftOperator): s3_to_redshift> on 2023-02-02 17:23:42.968181+00:00
[2023-02-02T17:24:47.160+0000] {standard_task_runner.py:55} INFO - Started process 24268 to run task
[2023-02-02T17:24:47.164+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag_prac', 's3_to_redshift', 'manual__2023-02-02T17:23:42.968181+00:00', '--job-id', '599', '--raw', '--subdir', 'DAGS_FOLDER/prac.py', '--cfg-path', '/tmp/tmpuor11mub']
[2023-02-02T17:24:47.165+0000] {standard_task_runner.py:83} INFO - Job 599: Subtask s3_to_redshift
[2023-02-02T17:24:47.204+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag_prac.s3_to_redshift manual__2023-02-02T17:23:42.968181+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-02-02T17:24:47.251+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag_prac
AIRFLOW_CTX_TASK_ID=s3_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-02-02T17:23:42.968181+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-02T17:23:42.968181+00:00
[2023-02-02T17:24:47.255+0000] {base.py:71} INFO - Using connection ID 'aws_default' for task execution.
[2023-02-02T17:24:47.257+0000] {base.py:71} INFO - Using connection ID 'aws_default' for task execution.
[2023-02-02T17:24:47.257+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2023-02-02T17:24:47.266+0000] {s3_to_redshift.py:164} INFO - Executing COPY command...
[2023-02-02T17:24:47.272+0000] {base.py:71} INFO - Using connection ID 'redshift_default' for task execution.
[2023-02-02T17:24:47.289+0000] {credentials.py:1251} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2023-02-02T17:24:47.619+0000] {sql.py:375} INFO - Running statement: 
                    COPY spotify.test 
                    FROM 's3://airflow-nk/listen_records_by_artists_test'
                    credentials
                    'aws_access_key_id=AKIA2RZBA5HRP7SVZGJC;aws_secret_access_key=***'
                    IAM_ROLE 'arn:aws:iam::725381868002:role/classspectrum'
			FORMAT AS PARQUET;
        , parameters: None
[2023-02-02T17:24:47.637+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 165, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib/python3.10/dist-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.10/dist-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.10/dist-packages/redshift_connector/core.py", line 1969, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'conflicting or redundant options', 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '442', 'R': 'FailIfConflictCredentialsExists'}
[2023-02-02T17:24:47.641+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=spotify_dag_prac, task_id=s3_to_redshift, execution_date=20230202T172342, start_date=20230202T172447, end_date=20230202T172447
[2023-02-02T17:24:47.653+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 599 for task s3_to_redshift ({'S': 'ERROR', 'C': '42601', 'M': 'conflicting or redundant options', 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '442', 'R': 'FailIfConflictCredentialsExists'}; 24268)
[2023-02-02T17:24:47.697+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-02T17:24:47.707+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
