[2023-02-03T17:02:07.165+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Spotify_etl_2.delete_bronze_logs scheduled__2023-02-02T17:00:00+00:00 [queued]>
[2023-02-03T17:02:07.171+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Spotify_etl_2.delete_bronze_logs scheduled__2023-02-02T17:00:00+00:00 [queued]>
[2023-02-03T17:02:07.171+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T17:02:07.171+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-02-03T17:02:07.171+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T17:02:07.184+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): delete_bronze_logs> on 2023-02-02 17:00:00+00:00
[2023-02-03T17:02:07.186+0000] {standard_task_runner.py:55} INFO - Started process 45608 to run task
[2023-02-03T17:02:07.190+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Spotify_etl_2', 'delete_bronze_logs', 'scheduled__2023-02-02T17:00:00+00:00', '--job-id', '649', '--raw', '--subdir', 'DAGS_FOLDER/practice.py', '--cfg-path', '/tmp/tmpr1gd6c1u']
[2023-02-03T17:02:07.191+0000] {standard_task_runner.py:83} INFO - Job 649: Subtask delete_bronze_logs
[2023-02-03T17:02:07.227+0000] {task_command.py:376} INFO - Running <TaskInstance: Spotify_etl_2.delete_bronze_logs scheduled__2023-02-02T17:00:00+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-02-03T17:02:07.274+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Spotify_etl_2
AIRFLOW_CTX_TASK_ID=delete_bronze_logs
AIRFLOW_CTX_EXECUTION_DATE=2023-02-02T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-02T17:00:00+00:00
[2023-02-03T17:02:07.288+0000] {credentials.py:1251} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2023-02-03T17:02:07.519+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/spotify_dag/practice.py", line 48, in delete_files
    for object in response['Contents']:
KeyError: 'Contents'
[2023-02-03T17:02:07.524+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_etl_2, task_id=delete_bronze_logs, execution_date=20230202T170000, start_date=20230203T170207, end_date=20230203T170207
[2023-02-03T17:02:07.535+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 649 for task delete_bronze_logs ('Contents'; 45608)
[2023-02-03T17:02:07.561+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-03T17:02:07.576+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
