[2023-01-26T14:02:35.178+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.glue_job scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-26T14:02:35.184+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.glue_job scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-26T14:02:35.184+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T14:02:35.184+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-26T14:02:35.185+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T14:02:35.197+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): glue_job> on 2023-01-26 12:00:00+00:00
[2023-01-26T14:02:35.200+0000] {standard_task_runner.py:55} INFO - Started process 2004 to run task
[2023-01-26T14:02:35.204+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'glue_job', 'scheduled__2023-01-26T12:00:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dags.py', '--cfg-path', '/tmp/tmp6jqhauaw']
[2023-01-26T14:02:35.206+0000] {standard_task_runner.py:83} INFO - Job 386: Subtask glue_job
[2023-01-26T14:02:35.248+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag.glue_job scheduled__2023-01-26T12:00:00+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-01-26T14:02:35.302+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=glue_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-26T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-26T12:00:00+00:00
[2023-01-26T14:02:35.324+0000] {credentials.py:1048} INFO - Found credentials from IAM Role: EC2_S3_Af
[2023-01-26T14:02:35.668+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/spotify_dag/spotify_dags.py", line 98, in GlueJobRun
    response = client.start_job_run(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConcurrentRunsExceededException: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded for SpotifyGlueJob
[2023-01-26T14:02:35.672+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=glue_job, execution_date=20230126T120000, start_date=20230126T140235, end_date=20230126T140235
[2023-01-26T14:02:35.682+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 386 for task glue_job (An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded for SpotifyGlueJob; 2004)
[2023-01-26T14:02:35.700+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-26T14:02:35.711+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
