[2022-12-21T13:38:55.829+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl scheduled__2022-12-21T06:00:00+00:00 [queued]>
[2022-12-21T13:38:55.836+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl scheduled__2022-12-21T06:00:00+00:00 [queued]>
[2022-12-21T13:38:55.836+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T13:38:55.836+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-21T13:38:55.836+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T13:38:55.848+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): spotify_etl> on 2022-12-21 06:00:00+00:00
[2022-12-21T13:38:55.851+0000] {standard_task_runner.py:55} INFO - Started process 2031 to run task
[2022-12-21T13:38:55.856+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'spotify_etl', 'scheduled__2022-12-21T06:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dags.py', '--cfg-path', '/tmp/tmpjxclieq3']
[2022-12-21T13:38:55.857+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask spotify_etl
[2022-12-21T13:38:55.897+0000] {task_command.py:376} INFO - Running <TaskInstance: spotify_dag.spotify_etl scheduled__2022-12-21T06:00:00+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2022-12-21T13:38:55.935+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-12-21T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-21T06:00:00+00:00
[2022-12-21T13:38:56.582+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/spotify_dag/spotify_dags.py", line 51, in find_songs
    file_path = 's3://airflow-nk/' + run_time + '.csv'
TypeError: can only concatenate str (not "datetime.datetime") to str
[2022-12-21T13:38:56.585+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=spotify_dag, task_id=spotify_etl, execution_date=20221221T060000, start_date=20221221T133855, end_date=20221221T133856
[2022-12-21T13:38:56.596+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 98 for task spotify_etl (can only concatenate str (not "datetime.datetime") to str; 2031)
[2022-12-21T13:38:56.629+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-21T13:38:56.639+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
