[2023-01-25T09:02:51.968+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practice.glue_job manual__2023-01-25T08:58:45.988349+00:00 [queued]>
[2023-01-25T09:02:51.985+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practice.glue_job manual__2023-01-25T08:58:45.988349+00:00 [queued]>
[2023-01-25T09:02:51.985+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T09:02:51.986+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-01-25T09:02:51.986+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T09:02:52.026+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): glue_job> on 2023-01-25 08:58:45.988349+00:00
[2023-01-25T09:02:52.029+0000] {standard_task_runner.py:55} INFO - Started process 18024 to run task
[2023-01-25T09:02:52.046+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'practice', 'glue_job', 'manual__2023-01-25T08:58:45.988349+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/practice.py', '--cfg-path', '/tmp/tmp07y5uen_']
[2023-01-25T09:02:52.047+0000] {standard_task_runner.py:83} INFO - Job 347: Subtask glue_job
[2023-01-25T09:02:52.136+0000] {task_command.py:376} INFO - Running <TaskInstance: practice.glue_job manual__2023-01-25T08:58:45.988349+00:00 [running]> on host ip-172-31-26-59.ap-northeast-2.compute.internal
[2023-01-25T09:02:52.282+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nywkim@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=practice
AIRFLOW_CTX_TASK_ID=glue_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-25T08:58:45.988349+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-25T08:58:45.988349+00:00
[2023-01-25T09:02:52.351+0000] {credentials.py:1048} INFO - Found credentials from IAM Role: EC2_S3_Af
[2023-01-25T09:02:52.938+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/spotify_dag/practice.py", line 29, in GlueJobRun
    response = client.start_job_run(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the StartJobRun operation: Please do not set Allocated Capacity if using Worker Type and Number of Workers.
[2023-01-25T09:02:52.951+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=practice, task_id=glue_job, execution_date=20230125T085845, start_date=20230125T090251, end_date=20230125T090252
[2023-01-25T09:02:52.994+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 347 for task glue_job (An error occurred (InvalidInputException) when calling the StartJobRun operation: Please do not set Allocated Capacity if using Worker Type and Number of Workers.; 18024)
[2023-01-25T09:02:53.012+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-25T09:02:53.044+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
